name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-windows:
    runs-on: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: npm run compile