name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: Build the app
        run: npm run compile