name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]
        node-version: [14.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install packages
        run: npm i
      - name: Build the app
        run: npm run compile
      - name: Run linter on src
        run: npx eslint src